name: weather
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:

  http: ^0.13.5
  fluttertoast: ^8.0.8
  ndialog: ^4.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  -assets/images/KL_skyline_no_haze.jpg